### ISSUE TITLE
T10: Fetch Products

### ISSUE THREAD

**Issue by irtassedat** [irtassedat/ecommerce#16]
- [x] **Fetch products**
    - [x] by **thunk action** and save it in the **product reducer**
    - [x] endpoint “/products“
    - [x] query parameters:
        - [ ] category? : optional. you can limit products by sending category id
        - [ ] filter?: optional. products can be filtered by the text
        - [ ] sort?: optional. products can be sorted by the fields “price:asc”, “price:desc” , “rating:asc”, “rating:desc”
- [ ] you should list products in the UI (shopping page)
- [x] while fetching products data, a loading spinner should be shown on the screen
- [ ] in response you will get Object like below:
   ```js{
      total: 185,
      products: [
         { ProductObject1 }, 
         { ProductObject2 }, 
         …
      ]
   }
   ```

**Comment by gokhanozdemir** [comment]
@irtassedat bizi assignee değil Pull request atarken review'a eklesen daha doğru olur. Assign ettiğin kişi, görevi yapması gereken kişi, reviewer gözden geçirip bakacak kişi demek.
