### ISSUE TITLE
T12: Product Detail Page implementation

### ISSUE THREAD

**Issue by irtassedat** [irtassedat/ecommerce#24]
- [ ] When a product is clicked it should navigate to Product Detail Page with proper URL
    - URL should be like: “/:category/:productId/:productNameSlug”
- [ ] Page should have back button

**Comment by gokhanozdemir** [comment]
https://v5.reactrouter.com/web/api/Link
https://v5.reactrouter.com/web/example/url-params
@irtassedat Batuhan ile beraber bu konulara bakabilirsiniz. Güzel olur.
